version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: Project04-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project04
    ports:
      - "3308:3306"
    networks:
      - mynetwork
    volumes:
      - ./mysql-data:/var/lib/mysql

  webapp:
    build:
      context: .
    container_name: Project04-webapp
    ports:
      - "8081:8080"
    networks:
      - mynetwork
    depends_on:
      - mysql
    environment:
      DATABASE_URL: jdbc:mysql://mysql:3306/project04

networks:
  mynetwork:
    driver: bridge
